### ISSUE TITLE
Android 10, MIUI: Neither downloading, nor viewing existing downloads

### ISSUE THREAD

**Issue by nognir** [Nonononoki/Hendroid#9] opened 2020-03-09 08:01 UTC
**Hendroid Version**:1.11.2

**Device/Android Version**:Xiaomi Pocophone F1/Android 10

**Issue details / Repro steps**:After upgrading to Android 10, downloading galleries and viewing downloaded galleries is broken. 
1.Choose a gallery
2.Try to download
3.Notice that "queue" icon changes to "play" icon immediately
4.Try to view. Receive pop-up "file not found in storage"
5.Go to "queue". Notice the "!" next to the gallery

On Hentoid, the same function works, as well as the viewing on existing libraries.

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by Nonononoki** [comment] 2020-03-09 12:33
Which site do you use?

**Comment by nognir** [comment] 2020-03-11 07:05
Retrieval fails regardless of source. Something is incompatible as far as storage management/permissions are concerned.

I repeat, same steps in Hentoid (ver 1.11.2) result in working retrieval.

**Comment by Nonononoki** [comment] 2020-03-12 19:16
Working on the Android Emulator with Android 10, downloading from Hitomi. Can't reproduce the error, so I can't fix it without a stack trace.

**Comment by nognir** [comment] 2020-03-12 22:58
Seems like a MIUI ROM issue about allowing write storage permission to folders (despite getting the permission when asked). The app works as advertised on another device, not running MIUI. I'll try and grab the logs or stack trace to pinpoint the issue.

**Comment by Badabing-Badaboop** [comment] 2020-03-22 11:20
Got the exact same problem here, Moto G7 plus, with stock Android, running Nova Launcher.
So it might be that the issue isn't with MIUI.

**Comment by PoorPocketsMcNewHold** [comment] 2020-04-07 15:43
I can confirm it wasn't with MIUI, as i've also had this issue on a crDroid Q build, on my herolte. The folder structure would still create, regardless if it was on the local storage, or an SD card.

**Comment by Nonononoki** [comment] 2020-04-08 06:52
Since so many people have custom ROMS, can a single one post their logcat?

**Comment by PoorPocketsMcNewHold** [comment] 2020-04-08 18:40
> Since so many people have custom ROMs, can a single one post their logcat?

Installed LineageOS 17.1 Q 
```
lineage_herolte-userdebug 10 QQ2A.200305.003 eng.ivanme.20200311.154050 test-keys
```
Because i've been kind of custom rom hoping and... Nah, It work.

I would like to ask for other where their "error" would be located, because on my end, using the default settings, it would be located to :
`/data/data/org.nonononoki.hendroid/app_/.Hentoid/websitename/doujinname/`
Which is a system folder, while the previous time, it would save in either the local storage or SD at :
`/storage/emulated/0/Android/data/org.nonononoki.hendroid/files/`

**Comment by ardumpl** [comment] 2020-04-14 00:08
Same like @PoorPocketsMcNewHold 
I had this issue on ColtOS Q (CrDroid Q based) for tissot (MI A1). After set to existing .Hendroid directory, it's restarted again and shows nothing, here for log file

[logcat_04-14-2020_06-53-00.txt](https://github.com/Nonononoki/Hendroid/files/4472445/logcat_04-14-2020_06-53-00.txt)

**Comment by Nonononoki** [comment] 2020-04-18 18:03
I couldn't find any solution, but the source code has been merged with the master of Hentoid. Can someone confirm that the problem still exist with the latest version? https://github.com/Nonononoki/Hendroid/releases/tag/1.11.4

**Comment by Nonononoki** [comment] 2020-04-25 09:09
So I upgraded to Android 10 and encountered some storage issues, but not this particular issue.
Can someone confirm that it's fixed?
https://github.com/Nonononoki/Hendroid/releases/tag/1.11.4.1

**Comment by nognir** [comment] 2020-05-01 08:16
I just tried the 1.11.4.1 version, and the issue on my end is fixed. Library and existing downloads are detected properly, downloads operating.

**Closed** 2020-05-04 07:22 UTC
